"""The structural gate: every public callable of RadDB has a test named after it.

The suite is organized **structurally**, not thematically: ``raddb/<module>.py`` is tested
by ``raddb/tests/test_<module>.py``, and every public callable in that module has a
``test_<callable>`` in that file.  This module checks that mapping mechanically by parsing
both sides with :mod:`ast`, so a new public function that ships without a test turns CI
red instead of going unnoticed.

Naming rules enforced here:

- a module-level function ``foo``     -> ``test_foo``
- a class ``Bar``                     -> ``test_Bar``
- a method ``Bar.baz``                -> ``test_Bar_baz``
- a dunder ``Bar.__len__``            -> ``test_Bar_len`` (see :data:`DUNDERS`)

Tests beyond this mandatory set are welcome and keep their own descriptive names; this
module only checks that nothing is *missing*.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

TESTS_DIR = Path(__file__).resolve().parent
PKG_DIR = TESTS_DIR.parent
REPO_ROOT = PKG_DIR.parent

MODULE_TO_TEST_FILE: dict[str, str] = {
    "raddb/__init__.py": "test_package_api.py",
    "raddb/_proj.py": "test__proj.py",
    "raddb/aoi.py": "test_aoi.py",
    "raddb/discovery.py": "test_discovery.py",
    "raddb/helper.py": "test_helper.py",
    "raddb/io_core.py": "test_io_core.py",
    "raddb/lut.py": "test_lut.py",
    "raddb/main.py": "test_main.py",
    "raddb/viz/__init__.py": "test_viz_init.py",
    "raddb/viz/interactive.py": "test_viz_interactive.py",
    "raddb/viz/plot.py": "test_viz_plot.py",
    # Source module (repo-relative) -> the test file that must cover it. The two ``__init__.py``
    # entries are special-cased: a literal ``test___init__.py`` is unreadable and the package root
    # and ``viz/`` would collide on the same name.
}

# Modules deliberately not covered — ``_version.py`` is generated by setuptools_scm.
SKIP_MODULES = {"raddb/_version.py"}

# Test files that cover no single source module.
SKIP_TEST_FILES = {"test_api_coverage.py"}

# Dunder methods that are part of the public surface, and their test-name suffix.
DUNDERS = {"__init__": "init", "__len__": "len", "__repr__": "repr"}

# Test files not yet written out, exempt from the per-callable check. The coarse half of the
# loop's ledger: one name is removed as each file is completed, so the gate tightens
# monotonically. Must be **empty** when the restructuring is finished.
PENDING_FILES: set[str] = set()

# Individual callables that are knowingly untested, as ``"<test_file>::<test_name>"``. The fine
# half of the ledger, for a callable inside an otherwise-finished file that could not be tested.
# Every entry needs a one-line reason beside it, and this must be **empty** when the
# restructuring is finished.
KNOWN_MISSING: set[str] = set()


def _source_modules() -> list[Path]:
    """Return every RadDB source module, excluding the test package itself.

    Returns
    -------
    list of pathlib.Path
        Absolute paths, sorted.
    """
    return sorted(p for p in PKG_DIR.rglob("*.py") if "tests" not in p.relative_to(PKG_DIR).parts)


def _test_name_for(qualname: str) -> str:
    """Map a callable's qualified name to the test name that must exist.

    Parameters
    ----------
    qualname : str
        Either ``"func"``, ``"Class"`` or ``"Class.method"``.

    Returns
    -------
    str
        The mandatory ``test_...`` function name.
    """
    if "." not in qualname:
        return f"test_{qualname}"
    cls, method = qualname.split(".", 1)
    return f"test_{cls}_{DUNDERS.get(method, method)}"


def _public_qualnames(path: Path) -> list[str]:
    """Return the public callables declared at the top level of ``path``.

    Nested functions and closures are ignored: only module-level ``def``/``class`` and,
    inside a public class, its methods.

    Parameters
    ----------
    path : pathlib.Path
        A Python source file.

    Returns
    -------
    list of str
        Qualified names, e.g. ``["open", "RadDB", "RadDB.open"]``.
    """
    names: list[str] = []
    for node in ast.parse(path.read_text(encoding="utf-8")).body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                names.append(node.name)
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            names.append(node.name)
            for sub in node.body:
                if not isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                if not sub.name.startswith("_") or sub.name in DUNDERS:
                    names.append(f"{node.name}.{sub.name}")
    return names


def _declared_tests(test_file: Path) -> set[str]:
    """Return every ``test_*`` function declared in ``test_file``.

    Both module-level test functions and methods of ``Test*`` classes count, so a ported
    legacy test grouped under a class still satisfies the gate.

    Parameters
    ----------
    test_file : pathlib.Path
        A test module.  A missing file yields an empty set.

    Returns
    -------
    set of str
        Test function names.
    """
    if not test_file.exists():
        return set()
    found: set[str] = set()
    for node in ast.walk(ast.parse(test_file.read_text(encoding="utf-8"))):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test_"):
            found.add(node.name)
    return found


def _expected_coverage() -> dict[str, set[str]]:
    """Build the full ``{test_file: {required test names}}`` mapping.

    Returns
    -------
    dict
        Keyed by test-file name, one entry per source module (empty set allowed).
    """
    expected: dict[str, set[str]] = {}
    for module in _source_modules():
        rel = module.relative_to(REPO_ROOT).as_posix()
        if rel in SKIP_MODULES:
            continue
        test_file = MODULE_TO_TEST_FILE[rel]
        expected.setdefault(test_file, set())
        expected[test_file] |= {_test_name_for(q) for q in _public_qualnames(module)}
    return expected


def test_every_module_has_a_test_file():
    """Every source module is mapped, and the mapped test file exists on disk."""
    unmapped = [
        m.relative_to(REPO_ROOT).as_posix()
        for m in _source_modules()
        if m.relative_to(REPO_ROOT).as_posix() not in MODULE_TO_TEST_FILE
        and m.relative_to(REPO_ROOT).as_posix() not in SKIP_MODULES
    ]
    assert unmapped == [], f"source modules with no entry in MODULE_TO_TEST_FILE: {unmapped}"

    absent = sorted(name for name in MODULE_TO_TEST_FILE.values() if not (TESTS_DIR / name).exists())
    assert absent == [], f"mapped test files that do not exist: {absent}"


def test_no_orphan_test_file():
    """No ``test_*.py`` exists whose source module is gone."""
    on_disk = {p.name for p in TESTS_DIR.glob("test_*.py")} - SKIP_TEST_FILES
    expected = set(MODULE_TO_TEST_FILE.values())
    assert on_disk - expected == set(), f"test files covering no source module: {sorted(on_disk - expected)}"


def test_every_public_callable_has_a_test():
    """Each public callable has a ``test_`` named after it, modulo the two ledgers."""
    missing: set[str] = set()
    for test_file, required in _expected_coverage().items():
        if test_file in PENDING_FILES:
            continue
        have = _declared_tests(TESTS_DIR / test_file)
        missing |= {f"{test_file}::{name}" for name in required - have}

    stale = KNOWN_MISSING - missing
    assert stale == set(), f"KNOWN_MISSING lists tests that now exist — remove them: {sorted(stale)}"
    assert missing == KNOWN_MISSING, f"public callables with no test: {sorted(missing - KNOWN_MISSING)}"


def test_pending_files_are_real():
    """A name in :data:`PENDING_FILES` must be a file we actually plan to write."""
    bogus = PENDING_FILES - set(MODULE_TO_TEST_FILE.values())
    assert bogus == set(), f"PENDING_FILES names unknown test files: {sorted(bogus)}"


def test_the_ledgers_are_empty():
    """Both ledgers must be empty once the restructuring is finished."""
    if PENDING_FILES or KNOWN_MISSING:
        pytest.xfail(f"{len(PENDING_FILES)} files pending, {len(KNOWN_MISSING)} callables untested")
    assert (set(), set()) == (PENDING_FILES, KNOWN_MISSING)
